//! Small building blocks shared by the views.

mod action_button;
mod column_header;
mod container_link;
mod create_field;
mod detail_panel;
mod detail_section;
mod drag_region;
mod empty_note;
mod group_card;
mod icon_button;
mod inline_error;
mod inline_notice;
mod key_values;
mod list_row;
mod page_header;
mod pill;
mod progress_bar;
pub mod scales;
mod segmented;
mod settings_card;
mod settings_row;
mod sparkline;
mod stat_tile;
mod status_dot;
mod swatch;
mod text_button;
mod titled_section;

pub use action_button::action_button;
pub use column_header::{Column, column_header};
pub use container_link::{container_link, state_color};
pub use create_field::create_field;
pub use detail_panel::{DetailHeader, detail_panel};
pub use detail_section::{detail_note, detail_section, key_values, map_or_note};
pub use drag_region::drag_region;
pub use empty_note::empty_note;
pub use group_card::group_card;
pub use icon_button::icon_button;
pub use inline_error::inline_error;
pub use inline_notice::inline_notice;
pub use key_values::{KeyValue, colored_key_values};
pub use list_row::list_row;
pub use page_header::page_header;
pub use pill::pill;
pub use progress_bar::progress_bar;
pub use segmented::{Segment, segmented};
pub use settings_card::settings_card;
pub use settings_row::settings_row;
pub use sparkline::{Scale, sparkline};
pub use stat_tile::{StatTile, stat_tile};
pub use status_dot::status_dot;
pub use swatch::swatch;
pub use text_button::{ButtonTone, text_button};
pub use titled_section::{section_note, titled_section};
